### ISSUE TITLE
there is no condition in encoder?

### ISSUE THREAD

**Issue by leondada** [ceh-2000/fed_cvae#71]
Hi, I have a small question. As far as I understand about CVAE, the encoder requires labels as inputs. Why does the conditional encoder in the code only take images as input?

**Comment by ceh-2000** [comment]
Hello! Thank you for reaching out with an astute observation. We chose not to provide labels explicitly to the CVAE’s encoder, but believe that training the CVAE with both the encoder and decoder end-to-end should implicitly deliver weak class signal back to the encoder. We predict that explicitly providing class labels to the encoder could play out two ways:
- It could improve performance by having the labels throughout the training procedure, improving latent embeddings and thus synthetic samples. We’re rather sure this would be the case for FedCVAE-Ens (one of our two proposed methods).
- It could affect knowledge distillation by disrupting the organization of latent space, which might affect FedCVAE-KD’s performance.

Either way, we don’t expect a major shift in performance, but this would be relatively easy to test and we welcome you to do so if you plan on benchmarking against either of our methods.
